# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who have a total_claim_amount greater than $1,000 and have a response of "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze the average total_claim_amount by each policy type and gender for customers who have responded "Yes" to the last marketing campaign. Write your conclusions.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [3]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   Customer                       10910 non-null  object
 2   State                          10279 non-null  object
 3   Customer Lifetime Value        10910 non-null  float64
 4   Response                       10279 non-null  object
 5   Coverage                       10910 non-null  object
 6   Education                      10910 non-null  object
 7   Effective To Date              10910 non-null  object
 8   EmploymentStatus               10910 non-null  object
 9   Gender                         10910 non-null  object
 10  Income                         10910 non-null  int64
 11  Location Code                  10910 non-null  object
 12  Marital Status                 10910 non-null  object
 13  Monthly Premium Auto           10910 non-null  int64
 14  Months Since Last Claim        10277 non-null  float64
 15  Months Since Policy Inception  10910 non-null  int64
 16  Number of Open Complaints      10277 non-null  float64
 17  Number of Policies             10910 non-null  int64
 18  Policy Type                    10910 non-null  object
 19  Policy                         10910 non-null  object
 20  Renew Offer Type               10910 non-null  object
 21  Sales Channel                  10910 non-null  object
 22  Total Claim Amount             10910 non-null  float64
 23  Vehicle Class                  10288 non-null  object
 24  Vehicle Size                   10288 non-null  object
 25  Vehicle Type                   5428 non-null   object
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

In [4]:
df.sample(25)

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
5283,5283,GJ59592,California,5318.896640,Yes,Basic,Bachelor,1/12/11,Employed,F,...,0.0,6,Corporate Auto,Corporate L2,Offer2,Call Center,321.600000,Four-Door Car,Small,NaN
260,260,MS11057,Oregon,9587.586583,No,Premium,Bachelor,1/31/11,Employed,M,...,0.0,4,Personal Auto,Personal L3,Offer1,Call Center,65.428481,Four-Door Car,Medsize,NaN
303,303,DN98431,Oregon,2535.321683,No,Basic,High School or Below,2/27/11,Unemployed,F,...,0.0,1,Corporate Auto,Corporate L3,Offer1,Branch,326.400000,Four-Door Car,Medsize,A
8367,8367,AJ89108,California,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
8146,8146,XM96138,California,11277.724880,No,Extended,Master,2/1/11,Employed,M,...,1.0,2,Personal Auto,Personal L1,Offer3,Agent,427.527310,Four-Door Car,Medsize,A
4766,4766,SE47384,California,5526.438887,No,Extended,Bachelor,2/6/11,Employed,F,...,0.0,1,Special Auto,Special L3,Offer3,Agent,657.600000,SUV,Medsize,A
9120,9120,QK31192,Arizona,4079.132667,No,Premium,High School or Below,2/18/11,Unemployed,M,...,0.0,1,Corporate Auto,Corporate L2,Offer4,Branch,631.124372,Two-Door Car,Medsize,A
7716,7716,MB32944,Nevada,2635.505781,No,Basic,Master,1/6/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer4,Branch,316.800000,NaN,NaN,NaN
4758,4758,XR97812,California,2345.084479,No,Basic,College,2/22/11,Unemployed,M,...,0.0,1,Personal Auto,Personal L3,Offer1,Agent,331.200000,Four-Door Car,Medsize,NaN
6438,6438,TP41703,NaN,7250.029606,NaN,Basic,Bachelor,2/1/11,Unemployed,M,...,0.0,2,Personal Auto,Personal L3,Offer4,Call Center,496.800000,Two-Door Car,Medsize,NaN
5562,5562,GY55415,Nevada,15725.250530,No,Premium,Bachelor,2/27/11,Unemployed,F,...,0.0,2,Corporate Auto,Corporate L1,Offer1,Web,1072.800000,SUV,Medsize,NaN
8993,8993,JC16991,Arizona,7423.899674,No,Basic,Master,2/12/11,Employed,F,...,0.0,2,Personal Auto,Personal L2,Offer1,Call Center,297.600000,Four-Door Car,Small,NaN
9623,9623,CX58204,Nevada,8079.833042,No,Basic,High School or Below,2/2/11,Disabled,F,...,0.0,6,Personal Auto,Personal L1,Offer1,Agent,734.400000,SUV,Medsize,NaN
9192,9192,AE60813,Oregon,4993.025273,No,Basic,College,2/17/11,Employed,F,...,1.0,7,Personal Auto,Personal L3,Offer4,Branch,101.341650,Four-Door Car,Medsize,NaN
7779,7779,DO83789,Arizona,5206.028448,No,Basic,College,2/2/11,Employed,F,...,0.0,4,Personal Auto,Personal L3,Offer4,Branch,312.000000,Four-Door Car,Small,NaN
991,991,MU57098,Oregon,5678.050167,Yes,Extended,Bachelor,1/19/11,Unemployed,F,...,0.0,3,Personal Auto,Personal L1,Offer2,Agent,364.800000,Four-Door Car,Small,A
2275,2275,TJ90326,California,13530.029060,No,Extended,Doctor,2/2/11,Employed,F,...,2.0,2,Personal Auto,Personal L3,Offer2,Call Center,180.555113,Four-Door Car,Small,NaN
5237,5237,EC94366,Oregon,3776.320768,No,Extended,Doctor,2/12/11,Medical Leave,M,...,0.0,1,Corporate Auto,Corporate L2,Offer2,Agent,291.536748,Four-Door Car,Medsize,NaN
3272,3272,VM34210,Washington,7399.032079,No,Basic,College,1/1/11,Unemployed,F,...,0.0,6,Personal Auto,Personal L2,Offer1,Web,337.617149,SUV,Medsize,NaN
3238,3238,BI76326,California,12275.343090,No,Premium,College,1/8/11,Employed,F,...,NaN,9,Personal Auto,Personal L3,Offer2,Call Center,430.505942,SUV,Small,NaN
3573,3573,VB26229,Arizona,8697.882675,No,Basic,Bachelor,1/31/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer2,Branch,350.400000,Four-Door Car,Medsize,NaN
425,425,DL53457,California,4605.036646,Yes,Basic,College,1/28/11,Medical Leave,F,...,0.0,9,Personal Auto,Personal L3,Offer2,Web,302.400000,Four-Door Car,Large,NaN
10327,10327,ZE59592,Oregon,5470.181751,No,Basic,College,1/6/11,Employed,M,...,0.0,3,Personal Auto,Personal L1,Offer3,Agent,746.107437,Two-Door Car,Medsize,A
9366,9366,VY90611,California,2499.036551,No,Basic,Master,1/27/11,Employed,F,...,0.0,1,Corporate Auto,Corporate L3,Offer2,Agent,364.622773,Two-Door Car,Small,A
756,756,VX85673,Arizona,4250.282624,Yes,Basic,High School or Below,1/18/11,Unemployed,F,...,1.0,7,Personal Auto,Personal L3,Offer1,Agent,292.800000,NaN,NaN,NaN

In [5]:
df = df.drop_duplicates()
df = df.dropna()

df

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
10,10,HG93801,Arizona,5154.764074,No,Extended,High School or Below,1/2/11,Employed,M,...,0.0,1,Corporate Auto,Corporate L3,Offer2,Branch,442.521087,SUV,Large,A
13,13,KR82385,California,5454.587929,No,Basic,Master,1/26/11,Employed,M,...,0.0,4,Personal Auto,Personal L3,Offer4,Call Center,331.200000,Two-Door Car,Medsize,A
16,16,FH51383,California,5326.677654,No,Basic,High School or Below,2/7/11,Employed,F,...,0.0,6,Personal Auto,Personal L3,Offer4,Call Center,300.528579,Two-Door Car,Large,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10902,10902,PP30874,California,3579.023825,No,Extended,High School or Below,1/24/11,Employed,F,...,2.0,1,Personal Auto,Personal L2,Offer2,Agent,655.200000,Four-Door Car,Medsize,A
10903,10903,SU71163,Arizona,2771.663013,No,Basic,College,1/7/11,Employed,M,...,4.0,1,Personal Auto,Personal L2,Offer2,Branch,355.200000,Two-Door Car,Medsize,A
10904,10904,QI63521,Nevada,19228.463620,No,Basic,High School or Below,2/24/11,Unemployed,M,...,0.0,2,Personal Auto,Personal L2,Offer1,Branch,897.600000,Luxury SUV,Medsize,A
10906,10906,KX53892,Oregon,5259.444853,No,Basic,College,1/6/11,Employed,F,...,0.0,6,Personal Auto,Personal L3,Offer2,Branch,273.018929,Four-Door Car,Medsize,A
10908,10908,WA60547,California,11971.977650,No,Premium,College,2/13/11,Employed,F,...,4.0,6,Personal Auto,Personal L1,Offer1,Branch,618.288849,SUV,Medsize,A

In [7]:
pd.set_option('display.max_columns', None)
df_mayor1000 = df[(df['Total Claim Amount'] > 1000) & (df['Response'] == 'Yes')]
df_mayor1000

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
236,236,YJ16163,Oregon,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,51643,Suburban,Single,283,16.0,43,0.0,1,Special Auto,Special L3,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
419,419,GW43195,Oregon,25807.063000,Yes,Extended,College,2/13/11,Employed,F,71210,Suburban,Married,214,8.0,89,1.0,2,Personal Auto,Personal L2,Offer1,Branch,1027.200000,Luxury Car,Small,A
442,442,IP94270,Arizona,13736.132500,Yes,Premium,Master,2/13/11,Disabled,F,16181,Suburban,Divorced,181,22.0,79,0.0,8,Personal Auto,Personal L2,Offer1,Web,1261.319869,SUV,Medsize,A
587,587,FJ28407,California,5619.689084,Yes,Premium,High School or Below,1/26/11,Unemployed,M,0,Suburban,Married,153,25.0,5,0.0,1,Personal Auto,Personal L1,Offer2,Web,1027.000029,SUV,Medsize,A
1527,1527,TU53781,Oregon,8427.172486,Yes,Extended,Bachelor,2/10/11,Employed,F,46503,Suburban,Divorced,215,4.0,21,1.0,1,Corporate Auto,Corporate L3,Offer1,Agent,1032.000000,Luxury SUV,Medsize,A
1809,1809,QO62792,Oregon,7840.165778,Yes,Extended,College,1/14/11,Employed,M,58414,Suburban,Single,210,7.0,24,2.0,1,Personal Auto,Personal L3,Offer2,Agent,1008.000000,Luxury SUV,Small,A
2027,2027,TA66375,Oregon,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,51643,Suburban,Single,283,16.0,43,0.0,1,Corporate Auto,Corporate L2,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
2125,2125,JC11405,Oregon,10963.957230,Yes,Premium,High School or Below,2/8/11,Employed,M,55687,Suburban,Divorced,276,33.0,91,0.0,1,Personal Auto,Personal L3,Offer1,Agent,1324.800000,Luxury SUV,Medsize,A
2865,2865,FH77504,California,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,51643,Suburban,Single,283,16.0,43,0.0,1,Personal Auto,Personal L3,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
3958,3958,KC26486,Arizona,8427.172486,Yes,Extended,Bachelor,2/10/11,Employed,F,46503,Suburban,Divorced,215,4.0,21,1.0,1,Personal Auto,Personal L2,Offer1,Agent,1032.000000,Luxury SUV,Medsize,A
4475,4475,WP58340,Arizona,10963.957230,Yes,Premium,High School or Below,2/8/11,Employed,M,55687,Suburban,Divorced,276,33.0,91,0.0,1,Personal Auto,Personal L2,Offer1,Agent,1324.800000,Luxury SUV,Medsize,A
4521,4521,LT72149,Nevada,5619.689084,Yes,Premium,High School or Below,1/26/11,Unemployed,M,0,Suburban,Married,153,25.0,5,0.0,1,Personal Auto,Personal L2,Offer2,Web,1027.000029,SUV,Medsize,A
4566,4566,TC99043,California,13736.132500,Yes,Premium,Master,2/13/11,Disabled,F,16181,Suburban,Divorced,181,22.0,79,0.0,8,Personal Auto,Personal L2,Offer1,Web,1261.319869,SUV,Medsize,A
5013,5013,GP83239,California,7840.165778,Yes,Extended,College,1/14/11,Employed,M,58414,Suburban,Single,210,7.0,24,2.0,1,Personal Auto,Personal L3,Offer2,Agent,1008.000000,Luxury SUV,Small,A
5331,5331,UT48216,Nevada,7840.165778,Yes,Extended,College,1/14/11,Employed,M,58414,Suburban,Single,210,7.0,24,2.0,1,Personal Auto,Personal L1,Offer2,Agent,1008.000000,Luxury SUV,Small,A
5489,5489,TQ84956,California,10963.957230,Yes,Premium,High School or Below,2/8/11,Employed,M,55687,Suburban,Divorced,276,33.0,91,0.0,1,Corporate Auto,Corporate L3,Offer1,Agent,1324.800000,Luxury SUV,Medsize,A
5896,5896,TY31217,Washington,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,51643,Suburban,Single,283,16.0,43,0.0,1,Personal Auto,Personal L3,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
7255,7255,PN98247,California,7840.165778,Yes,Extended,College,1/14/11,Employed,M,58414,Suburban,Single,210,7.0,24,2.0,1,Personal Auto,Personal L3,Offer2,Agent,1008.000000,Luxury SUV,Small,A
8340,8340,MJ51323,Oregon,8427.172486,Yes,Extended,Bachelor,2/10/11,Employed,F,46503,Suburban,Divorced,215,4.0,21,1.0,1,Personal Auto,Personal L2,Offer1,Agent,1032.000000,Luxury SUV,Medsize,A
8367,8367,AJ89108,California,11009.130490,Yes,Premium,Bachelor,1/24/11,Employed,F,51643,Suburban,Single,283,16.0,43,0.0,1,Personal Auto,Personal L3,Offer2,Agent,1358.400000,Luxury Car,Medsize,A
8505,8505,DT77901,Oregon,10179.717040,Yes,Premium,Bachelor,1/5/11,Retired,F,14290,Suburban,Married,271,20.0,40,0.0,1,Personal Auto,Personal L3,Offer1,Agent,1300.800000,Luxury SUV,Medsize,A
8662,8662,YU86361,Washington,19160.989940,Yes,Extended,Master,2/20/11,Employed,F,22705,Suburban,Divorced,239,19.0,59,0.0,7,Personal Auto,Personal L1,Offer2,Agent,1294.700423,Luxury SUV,Medsize,A
8835,8835,XT93203,California,10963.957230,Yes,Premium,High School or Below,2/8/11,Employed,M,55687,Suburban,Divorced,276,33.0,91,0.0,1,Personal Auto,Personal L3,Offer1,Agent,1324.800000,Luxury SUV,Medsize,A
9498,9498,IV54766,Oregon,19160.989940,Yes,Extended,Master,2/20/11,Employed,F,22705,Suburban,Divorced,239,19.0,59,0.0,7,Personal Auto,Personal L1,Offer2,Agent,1294.700423,Luxury SUV,Medsize,A
9581,9581,GD55093,California,19160.989940,Yes,Extended,Master,2/20/11,Employed,F,22705,Suburban,Divorced,239,19.0,59,0.0,7,Personal Auto,Personal L1,Offer2,Agent,1294.700423,Luxury SUV,Medsize,A
10009,10009,YP53257,Oregon,10179.717040,Yes,Premium,Bachelor,1/5/11,Retired,F,14290,Suburban,Married,271,20.0,40,0.0,1,Personal Auto,Personal L3,Offer1,Agent,1300.800000,Luxury SUV,Medsize,A
10708,10708,CK39096,Oregon,5619.689084,Yes,Premium,High School or Below,1/26/11,Unemployed,M,0,Suburban,Married,153,25.0,5,0.0,1,Personal Auto,Personal L3,Offer2,Web,1027.000029,SUV,Medsize,A

In [30]:
df_yes = df[df["Response"] == "Yes"]
pivot_table = pd.pivot_table(df_yes, values='Total Claim Amount', index=['Policy Type', 'Gender'], aggfunc='mean')
pivot_table

                       Total Claim Amount
Policy Type    Gender
Corporate Auto F               404.104008
               M               391.370774
Personal Auto  F               457.056315
               M               472.489180
Special Auto   F               495.689401
               M               368.523035

In [39]:
state_customer_counts = df['State'].value_counts()
states_mas_500 = state_customer_counts[state_customer_counts > 500]
states_mas_500

State
California    1552
Oregon        1281
Arizona        868
Name: count, dtype: int64

In [27]:
indice_stats = df.groupby(['Education', 'Gender'])['Customer Lifetime Value'].agg(['max', 'min', 'median'])
indice_stats

                                     max          min       median
Education            Gender
Bachelor             F       58753.88046  1904.000852  5752.485185
                     M       67907.27050  2030.783687  5797.377350
College              F       61850.18803  2004.350666  5642.596077
                     M       44795.46942  1918.119700  6005.847375
Doctor               F       44856.11397  2395.570000  5789.850900
                     M       32677.34284  2267.604038  5843.989737
High School or Below F       55277.44589  2150.178588  5978.754765
                     M       83325.38119  2132.771675  6081.481291
Master               F       51016.06704  2417.777032  5714.165863
                     M       50568.25912  2357.503128  5512.342258

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [ ]:
# your code goes here